### ISSUE TITLE
Add a keyboard help dialog

### ISSUE THREAD

**Issue by samreid** [phetsims/waves-intro#20]

**Comment by zepumph** [comment]
@emily-phet do you think this is reasonable to patch into the RC?

![image](https://user-images.githubusercontent.com/6856943/96182338-d0e48600-0ee1-11eb-86e1-58676556ff14.png)

**Comment by zepumph** [comment]
@emily-phet said on slack:

>During the design process for Waves Intro, it was decided not to include the keyboard help dialog, etc. into the work. With only partial keyboard support, we wouldn't consider it fully keyboard accessible, and so it wouldn't get that designation, etc. on the webpage. Since there will need to be more work done to make it fully accessible, and that would require some specialty interactions. If we made the keyboard help dialog now it, it would need to acknowledge the sim is not fully keyboard accessible, and would have to be re-done when the sim is fully keyboard accessible, to include the new interactions. All the current keyboard interactions implemented are the most standard ones anyway, so less likely to require someone to look for help.

I'll revert the change to master until we have complete keyboard nav implemented. Thanks for the refresher @emily-phet.

**Comment by zepumph** [comment]
Tagging @loganbraywork for understanding. @samreid feel free to close.

**Comment by emily-phet** [comment]
It's a good catch, since this decision was likely not documented in an obvious place, and good to know it's so quick to put together a simple keyboard help dialog.

I think this is the right decision though, to not include it, to minimize ambiguity about what we're considering fully keyboard accessible, and sims like this where it was relatively straightforward to provide some support and a learning opportunity for multiple developers to work on some keyboard implementation.
